// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftybijnvprdzwgtkwtzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0eWJpam52cHJkendndGt3dHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2Nzg1NDMsImV4cCI6MjA1NjI1NDU0M30.vb0XsyZwJo1jC2QUKTxxPWxfkrXXZI6DQ8aC9eXDXns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);